# Generate Inventory
### This notebook is used to showcase how the synthetic events dataset is generated

In [1]:
from datetime  import datetime
from pprint    import pprint

import pandas  as pd
import numpy   as np
import seaborn as sns
import polars  as pl

import os

default_path = os.getcwd()

In [2]:
# Run this cell in order to return to the defaulted working path
#os.chdir(path = default_path)

In [3]:
# Get the default or root folder of the user's system in case that any other person needs to run this setup
while not os.getcwd().endswith('Web Scraper'):
    os.chdir('..')
    if os.getcwd().endswith('Users'):
        print("Unable to find the root directory")
        break
users_default_path = os.getcwd()

In [13]:
# Grab all the directories
data_path   = os.path.join(users_default_path,'Data')

# Grab all the files
steam_games_path = os.path.join(data_path,'steam_games.csv.gzip')
video_games_path = os.path.join(data_path,'games.csv.gzip')
nyc_events_path  = os.path.join(data_path,'nyc_events.csv.gzip')

In [22]:
steam_games = pd.read_csv(steam_games_path, compression='gzip')
print(steam_games.shape)
steam_games.head(n =2)

(71429, 21)

,steam_appid,name,developers,publishers,categories,genres,required_age,n_achievements,platforms,is_released,...,additional_content,total_reviews,total_positive,total_negative,review_score,review_score_desc,positive_percentual,metacritic,is_free,price_initial (USD)
0,2719580,勇者の伝説の勇者,['ぽけそう'],['ぽけそう'],"['Single-player', 'Family Sharing']","['Casual', 'Indie']",0,0,['windows'],True,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.99
1,2719590,Light No Fire,['Hello Games'],['Hello Games'],"['Single-player', 'Multi-player', 'Co-op', 'On...","['Action', 'Adventure']",0,0,['windows'],False,...,[],0,0,0,0.0,No user reviews,0.0,0,False,0.00

In [30]:
video_games = pd.read_csv(video_games_path, compression='gzip')
video_games.drop(labels=0,inplace=True)
print(video_games.shape)
print(video_games.columns)
video_games.head(n = 2)

(1511, 14)
Index(['Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating', 'Times Listed',
       'Number of Reviews', 'Genres', 'Summary', 'Reviews', 'Plays', 'Playing',
       'Backlogs', 'Wishlist'],
      dtype='object')

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K

In [21]:
nyc_events = pd.read_csv(nyc_events_path, compression = 'gzip')
print(nyc_events.shape)
nyc_events.head(n = 2)

(21002, 13)

,Unnamed: 0,Event ID,Event Name,Start Date/Time,End Date/Time,Event Agency,Event Type,Event Borough,Event Location,Event Street Side,Street Closure Type,Community Board,Police Precinct
0,0,449943,Cortelyou Greenmarket Sunday,2019-01-06T08:00:00.000,2019-12-29T17:00:00.000,Street Activity Permit Office,Farmers Market,Brooklyn,CORTELYOU ROAD between RUGBY ROAD and ARGYLE ...,North,Sidewalk and Curb Lane Closure,"14,","70,"
1,1,449945,Columbia Greenmarket Thursday and Sunday,2019-01-03T08:00:00.000,2019-12-29T17:00:00.000,Street Activity Permit Office,Farmers Market,Manhattan,BROADWAY between WEST 114 STREET and WEST 1...,East,Sidewalk and Curb Lane Closure,"9,","26,"

In [38]:
(nyc_events['Event Type'].value_counts().items)

<bound method Series.items of Event Type
Sport - Youth                     13821
Sport - Adult                      3910
Special Event                      2594
Farmers Market                      225
Parade                               70
Production Event                     61
Block Party                          53
Sidewalk Sale                        52
Religious Event                      49
Street Event                         46
Plaza Partner Event                  31
Miscellaneous                        19
Plaza Event                          12
Theater Load in and Load Outs        12
Single Block Festival                 9
Athletic Race / Tour                  8
Stickball                             8
Street Festival                       7
Weekend Walk                          4
Health Fair                           4
Embargo                               3
Shooting Permit                       2
Public Program / Exhibitions          1
Clean-Up                              1
Name: count, dtype: int64>